query ($id: ID!) {
  person(id: $id) {
    data {
      id
      attributes {
        slug
        name
        surname
        gender
        email
        phone
        birth_date
      }
    }
  }
}
